### PR TITLE
Pull request for code review

### PR DESCRIPTION
**Pull request by dili021**
Something went wrong with the stickler setup. No issues appearing on GitHub/repo/issues, nor locally.
*edit: stickler works fine now, linter errors fixed.
*edit 2: made the changes required in the code review

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :red_circle:  [Changes Required] :red_circle: 
___
Hi @dili021  and @javitocor :wave: ,
Project contains a readme, PR contains the issue you have faced with the stickler. No comment piece of code. Awesome initiative :wave:. But just figured out some issues that kept me away from approving this project :disappointed:. But I am sure that you will cover them easily :sunglasses: .
___
#### Please follow the instructions below to complete the project.
___
### :spades: Mandatory Changes :spades: 
___
1. A configured linter is really important. Let me remind you the process. So that you can check it again. Go through this [link](https://github.com/microverseinc/linters-config/tree/master/css). Make sure that you have performed No. 1 & 2 task.
2. The Products logo contains their respective texts. But they are missing in here. So you have to add those.
---> Your one
image
---> Actual one:
image
3. Compare to original one The the space on the marked place looks to much. can you reduce it a little bit.
image
4. The  text on the footer should be divided into several lines. Check the [original one](https://accounts.intuit.com/signup.html).
image
___
### :clubs: [Optional Changes] :clubs: 
___
1. Can you enclose the fieldset inside a form tag. I think it will make code more readable. Though fieldset can be used separately. Just to improve the code readability :slightly_smiling_face: .
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by shshamim63** [comment]
## Status :eye: [Changes Required] :eye:
___
Hi @dili021 and @javitocor :wave: ,
Its me again. Awesome job. Project contains a descriptive readme.  Code looks neat and clean. Items are rendering on the place, where they should. But one issue, just issue kept me from approving this project. 
___
### [Mandatory Change]
1. You have to check HTML markup with this validator https://validator.w3.org/#validate_by_upload. And I saw 3 errors. Please resolve them.
___
### [Optional Changes]
___
1. You can make your files more organized, Maybe by creating a folder names assets. Which will contain image and style folder. style folder will contain the css file. Organizing files is aloso a part of good programming.
___
### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat hossain

**Comment by dili021** [comment]
Where is it showing the errors?
image

**Comment by shshamim63** [comment]
## Status :heavy_check_mark: [Approved] :heavy_check_mark: 
___
Covered all the changes asked in previous review. There are no issues. So the project is complete.
___
This :+1: is from me. You can go ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Pull request merged**
